server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    generate-ddl: true
    database: mysql
##    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
feign:
  hystrix:
    enabled: true
client:
  key: 959e2be19ce13df290c15d194387bab1
  grant_type: authorization_code
  redirect_uri: http://localhost:8080/kakao/info
token:
  expiration_time: 86400000
  secret: userToken